### ISSUE TITLE
Architec practica desarrollo de software

### ISSUE THREAD

**Issue by Julissamigdalia** [SistemasTecTlaxiaco/actividad-3-practica-architect-Julissamigdalia#1]
[Architec practica De 1.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-architect-Julissamigdalia/files/12554122/Architec.practica.De.1.pdf)

**Comment by YaelStO** [comment]
Buen trabajo 20/20

**Comment by josealfredo79** [comment]
Hay que evaluar bien por favor.... @YaelStO

**Comment by YaelStO** [comment]
Ofrezco una disculpa profe, 16/20

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado...
